from __future__ import annotations

from decimal import Decimal
from typing import Protocol


class WalletRepo(Protocol):
    async def ensure_wallet(self, user_id: int) -> dict: ...

    async def get_wallet(self, user_id: int) -> dict | None: ...

    async def credit_available(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def debit_available(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def freeze(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def unfreeze(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def transfer_available_to_margin(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def release_margin_to_available(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def apply_trade_cashflow(
        self,
        *,
        user_id: int,
        side: str,
        gross_amount_usd: Decimal,
        fee_usd: Decimal,
        reserved_balance_released_usd: Decimal,
        reserved_margin_released_usd: Decimal,
    ) -> None: ...

    async def credit_pending(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def debit_pending(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def pending_to_available(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def available_to_pending(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def credit_settlement(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def debit_settlement(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def settlement_to_available(self, user_id: int, amount_usd: Decimal) -> None: ...

    async def get_margin_account(self, user_id: int) -> dict | None: ...

    async def set_margin_mode(self, user_id: int, mode: str) -> dict: ...

    async def set_leverage(self, user_id: int, leverage: Decimal) -> dict: ...

    async def update_margin_account(self, user_id: int, **kwargs: object) -> dict: ...
